# Generated by Django 4.2.7 on 2023-11-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.CharField(choices=[('full', 'Полный пакет'), ('free', 'Бесплатный')], default='free', max_length=30),
        ),
    ]
