# Generated by Django 4.2.7 on 2023-11-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(choices=[(True, 'Полный пакет'), (False, 'Бесплатный')], default=False),
        ),
    ]
