# Generated by Django 4.2.7 on 2023-11-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_paid',
        ),
    ]
