# Generated by Django 4.2.7 on 2023-11-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=10, unique=True, verbose_name='Сгенерированная ссылка'),
        ),
    ]
