# Generated by Django 4.2.7 on 2023-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_link_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=10, unique=True, verbose_name='Укороченная ссылка'),
        ),
    ]
